### ISSUE TITLE
Javascript asíncrono en Node

### ISSUE THREAD

**Issue by atuells-apium** [barcelona-js/node#10]
---
level:  advanced
language: es
twitter: YourTwitterHandle
month: March

---

Como escribir código javascript asíncrono en nodejs que sea legible y no caer en el "callback hell".

**Comment by PatrickHeneise** [comment]
Hi! Can you give the talk on March 25?

**Comment by atuells-apium** [comment]
That's the idea

**Comment by PatrickHeneise** [comment]
Perfect, thanks!

**Comment by PatrickHeneise** [comment]
Sorry, there are some problems with the github delivery to our web server. :(

**Comment by PatrickHeneise** [comment]
wow, seems like Spanish is breaking GitHub web hooks ...

**Comment by PatrickHeneise** [comment]
Thanks!
