### ISSUE TITLE
syncorm: A different way to access the database.

### ISSUE THREAD

**Issue by jbaylina** [barcelona-js/node#14]
---
level: advanced
language: en/es/ca (as you want)
twitter: @jbaylina
month: March/April

---

syncorm is an orm that maintains a synchronized copy of the database in memory. You can query and modify the database directly with regular javascrit objects. syncorm will synchronize all the changes with the real mysql database in a transaction controlled manner. (bidirectionaly).

The project is already running in a production  project.

The Idea of the talk will consist to create a simple REST api with a MYSQL master detail table structure.

Duration: 45' should be enough.

You can check and learn more about syncorm here:

https://github.com/jbaylina/syncorm

**Comment by PatrickHeneise** [comment]
This is still on for next week, right?

**Comment by jbaylina** [comment]
Yes. Unless you preffer another day...
El dia 20/04/2015 16.16, "Patrick Heneise" <notifications@github.com> va
escriure:

**Comment by PatrickHeneise** [comment]
Nope, all good! :+1:

**Comment by PatrickHeneise** [comment]
Please keep it within 30 minutes.
